/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'mains' : null } |
  { 'desserts' : null } |
  { 'starters' : null } |
  { 'drinks' : null };
export type CuisineType = { 'tacos' : null } |
  { 'chinese' : null } |
  { 'sushi' : null } |
  { 'indian' : null } |
  { 'burgers' : null } |
  { 'pizza' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'restaurantId' : bigint,
  'category' : Category,
  'price' : bigint,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : Status,
  'deliveryAddress' : string,
  'total' : bigint,
  'deliveryFee' : bigint,
  'restaurantId' : bigint,
  'timestamp' : Time,
  'phone' : string,
  'items' : Array<OrderItem>,
  'subtotal' : bigint,
}
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'price' : bigint,
  'menuItemId' : bigint,
}
export interface Restaurant {
  'id' : bigint,
  'deliveryFee' : bigint,
  'minOrder' : bigint,
  'name' : string,
  'cuisineType' : CuisineType,
  'description' : string,
  'isOpen' : boolean,
  'deliveryTime' : bigint,
  'location' : string,
  'avgRating' : bigint,
}
export type Status = { 'preparing' : null } |
  { 'pending' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getMenuItems' : ActorMethod<[bigint], Array<MenuItem>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getRestaurant' : ActorMethod<[bigint], Restaurant>,
  'getRestaurants' : ActorMethod<[], Array<Restaurant>>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, Array<OrderItem>],
    bigint
  >,
  'updateOrderStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];