/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'preparing' : IDL.Null,
  'pending' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
  'menuItemId' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : Status,
  'deliveryAddress' : IDL.Text,
  'total' : IDL.Nat,
  'deliveryFee' : IDL.Nat,
  'restaurantId' : IDL.Nat,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'subtotal' : IDL.Nat,
});
export const Category = IDL.Variant({
  'mains' : IDL.Null,
  'desserts' : IDL.Null,
  'starters' : IDL.Null,
  'drinks' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'restaurantId' : IDL.Nat,
  'category' : Category,
  'price' : IDL.Nat,
});
export const CuisineType = IDL.Variant({
  'tacos' : IDL.Null,
  'chinese' : IDL.Null,
  'sushi' : IDL.Null,
  'indian' : IDL.Null,
  'burgers' : IDL.Null,
  'pizza' : IDL.Null,
});
export const Restaurant = IDL.Record({
  'id' : IDL.Nat,
  'deliveryFee' : IDL.Nat,
  'minOrder' : IDL.Nat,
  'name' : IDL.Text,
  'cuisineType' : CuisineType,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'deliveryTime' : IDL.Nat,
  'location' : IDL.Text,
  'avgRating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMenuItems' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getRestaurant' : IDL.Func([IDL.Nat], [Restaurant], ['query']),
  'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
      [IDL.Nat],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({
    'preparing' : IDL.Null,
    'pending' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
    'menuItemId' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : Status,
    'deliveryAddress' : IDL.Text,
    'total' : IDL.Nat,
    'deliveryFee' : IDL.Nat,
    'restaurantId' : IDL.Nat,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'subtotal' : IDL.Nat,
  });
  const Category = IDL.Variant({
    'mains' : IDL.Null,
    'desserts' : IDL.Null,
    'starters' : IDL.Null,
    'drinks' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'restaurantId' : IDL.Nat,
    'category' : Category,
    'price' : IDL.Nat,
  });
  const CuisineType = IDL.Variant({
    'tacos' : IDL.Null,
    'chinese' : IDL.Null,
    'sushi' : IDL.Null,
    'indian' : IDL.Null,
    'burgers' : IDL.Null,
    'pizza' : IDL.Null,
  });
  const Restaurant = IDL.Record({
    'id' : IDL.Nat,
    'deliveryFee' : IDL.Nat,
    'minOrder' : IDL.Nat,
    'name' : IDL.Text,
    'cuisineType' : CuisineType,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'deliveryTime' : IDL.Nat,
    'location' : IDL.Text,
    'avgRating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMenuItems' : IDL.Func([IDL.Nat], [IDL.Vec(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getRestaurant' : IDL.Func([IDL.Nat], [Restaurant], ['query']),
    'getRestaurants' : IDL.Func([], [IDL.Vec(Restaurant)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem)],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };