/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    id: bigint;
    name: string;
    description: string;
    restaurantId: bigint;
    category: Category;
    price: bigint;
}
export type Time = bigint;
export interface OrderItem {
    name: string;
    quantity: bigint;
    price: bigint;
    menuItemId: bigint;
}
export interface Restaurant {
    id: bigint;
    deliveryFee: bigint;
    minOrder: bigint;
    name: string;
    cuisineType: CuisineType;
    description: string;
    isOpen: boolean;
    deliveryTime: bigint;
    location: string;
    avgRating: bigint;
}
export interface Order {
    id: bigint;
    customerName: string;
    status: Status;
    deliveryAddress: string;
    total: bigint;
    deliveryFee: bigint;
    restaurantId: bigint;
    timestamp: Time;
    phone: string;
    items: Array<OrderItem>;
    subtotal: bigint;
}
export enum Category {
    mains = "mains",
    desserts = "desserts",
    starters = "starters",
    drinks = "drinks"
}
export enum CuisineType {
    tacos = "tacos",
    chinese = "chinese",
    sushi = "sushi",
    indian = "indian",
    burgers = "burgers",
    pizza = "pizza"
}
export enum Status {
    preparing = "preparing",
    pending = "pending",
    outForDelivery = "outForDelivery",
    delivered = "delivered"
}
export interface backendInterface {
    getAllOrders(): Promise<Array<Order>>;
    getMenuItems(restaurantId: bigint): Promise<Array<MenuItem>>;
    getOrder(id: bigint): Promise<Order>;
    getRestaurant(id: bigint): Promise<Restaurant>;
    getRestaurants(): Promise<Array<Restaurant>>;
    placeOrder(restaurantId: bigint, customerName: string, deliveryAddress: string, phone: string, items: Array<OrderItem>): Promise<bigint>;
    updateOrderStatus(id: bigint, status: Status): Promise<void>;
}
import type { Category as _Category, CuisineType as _CuisineType, MenuItem as _MenuItem, Order as _Order, OrderItem as _OrderItem, Restaurant as _Restaurant, Status as _Status, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItems(arg0: bigint): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_Order_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_Order_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurant(arg0: bigint): Promise<Restaurant> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurant(arg0);
                return from_candid_Restaurant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurant(arg0);
            return from_candid_Restaurant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRestaurants(): Promise<Array<Restaurant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRestaurants();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRestaurants();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: Array<OrderItem>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_Status_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_Status_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CuisineType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CuisineType): CuisineType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Restaurant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Restaurant): Restaurant {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    deliveryFee: bigint;
    minOrder: bigint;
    name: string;
    cuisineType: _CuisineType;
    description: string;
    isOpen: boolean;
    deliveryTime: bigint;
    location: string;
    avgRating: bigint;
}): {
    id: bigint;
    deliveryFee: bigint;
    minOrder: bigint;
    name: string;
    cuisineType: CuisineType;
    description: string;
    isOpen: boolean;
    deliveryTime: bigint;
    location: string;
    avgRating: bigint;
} {
    return {
        id: value.id,
        deliveryFee: value.deliveryFee,
        minOrder: value.minOrder,
        name: value.name,
        cuisineType: from_candid_CuisineType_n13(_uploadFile, _downloadFile, value.cuisineType),
        description: value.description,
        isOpen: value.isOpen,
        deliveryTime: value.deliveryTime,
        location: value.location,
        avgRating: value.avgRating
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _Status;
    deliveryAddress: string;
    total: bigint;
    deliveryFee: bigint;
    restaurantId: bigint;
    timestamp: _Time;
    phone: string;
    items: Array<_OrderItem>;
    subtotal: bigint;
}): {
    id: bigint;
    customerName: string;
    status: Status;
    deliveryAddress: string;
    total: bigint;
    deliveryFee: bigint;
    restaurantId: bigint;
    timestamp: Time;
    phone: string;
    items: Array<OrderItem>;
    subtotal: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_Status_n4(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        total: value.total,
        deliveryFee: value.deliveryFee,
        restaurantId: value.restaurantId,
        timestamp: value.timestamp,
        phone: value.phone,
        items: value.items,
        subtotal: value.subtotal
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    restaurantId: bigint;
    category: _Category;
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    restaurantId: bigint;
    category: Category;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        restaurantId: value.restaurantId,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mains: null;
} | {
    desserts: null;
} | {
    starters: null;
} | {
    drinks: null;
}): Category {
    return "mains" in value ? Category.mains : "desserts" in value ? Category.desserts : "starters" in value ? Category.starters : "drinks" in value ? Category.drinks : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tacos: null;
} | {
    chinese: null;
} | {
    sushi: null;
} | {
    indian: null;
} | {
    burgers: null;
} | {
    pizza: null;
}): CuisineType {
    return "tacos" in value ? CuisineType.tacos : "chinese" in value ? CuisineType.chinese : "sushi" in value ? CuisineType.sushi : "indian" in value ? CuisineType.indian : "burgers" in value ? CuisineType.burgers : "pizza" in value ? CuisineType.pizza : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
}): Status {
    return "preparing" in value ? Status.preparing : "pending" in value ? Status.pending : "outForDelivery" in value ? Status.outForDelivery : "delivered" in value ? Status.delivered : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Restaurant>): Array<Restaurant> {
    return value.map((x)=>from_candid_Restaurant_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    preparing: null;
} | {
    pending: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} {
    return value == Status.preparing ? {
        preparing: null
    } : value == Status.pending ? {
        pending: null
    } : value == Status.outForDelivery ? {
        outForDelivery: null
    } : value == Status.delivered ? {
        delivered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
